ondraw=true
if(type==2)
{
    direction=l_direction
    speed=wl_speed
    gravity=wl_gravity
    gravity_direction=wl_gravity_direction
}
else
{
	/*
	light_obj=instance_create_depth(x,y,depth,objLightLine)
	light_obj.Set(l_wide*3,l_direction,l_long,l_colora,1)
	light_obj.Follow(id,0,0,false,true)
	*/
}